tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "linuxbrew/xorg"
brew "zplug"
brew "anyenv"
brew "openssl@1.1"
brew "libffi"
brew "libyaml"
brew "docker-compose"
brew "fzf"
brew "gawk"
brew "ghq"
brew "hello"
brew "hub"
brew "keychain"
brew "ripgrep"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "vim"
brew "xclip" if OS.linux?
brew "zsh"
brew "gibo"
if OS.mac?
  brew "reattach-to-user-namespace"
  brew 'coreutils'
  brew 'gawk'
  brew 'gnu-sed'
end
